// File generated from our OpenAPI spec
namespace Paayes
{
    using Newtonsoft.Json;

    public class ChargePaymentMethodDetailsGrabpay : PaayesEntity<ChargePaymentMethodDetailsGrabpay>
    {
        /// <summary>
        /// Unique transaction id generated by GrabPay.
        /// </summary>
        [JsonProperty("transaction_id")]
        public string TransactionId { get; set; }
    }
}
